from . import course
from . import student
from . import career
from . import academic_session
from . import term_scheme
from . import campus
from . import degree
from . import academy_program
from . import admission_register
from . import aggregate_calculation
from . import student_application
from . import academy_test
from . import test_score
from . import academy_seat_allocation
from . import merit_selection_register
from . import res_users
from . import res_config_settings